//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preço
    {
        public int CódigoEquipamento { get; set; }
        public decimal Valor { get; set; }
        public string TipoDuração { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public int NumeroSerie { get; set; }
    
        public virtual Equipamento Equipamento { get; set; }
    }
}
