//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promoção
    {
        public int NumeroIdentificador { get; set; }
        public string Descrição { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
    
        public virtual Desconto Desconto { get; set; }
        public virtual TempoExtra TempoExtra { get; set; }
    }
}
