//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempoExtra
    {
        public int NumeroIdentificadorPromoção { get; set; }
        public int FracçãoExtra { get; set; }
        public string TipoDuração { get; set; }
    
        public virtual Promoção Promoção { get; set; }
    }
}
